server:
  port: 8484

spring:
  application:
    name: psregistry

psregistry:
  serverList:
    - http://127.0.0.1:8484
    - http://127.0.0.1:8485
    - http://127.0.0.1:8486

logging:
  level:
    root: INFO